### ISSUE TITLE
Add exclusion for `on_slave`

### ISSUE THREAD

**Issue by rcclemente** [zendesk/term-check#17]
We use `on_slave` for doing queries with our replica dbs

https://github.com/zendesk/term-check/blob/87c7829fdc61715e8a9dc2f5a136f8d54a622722/config.yaml#L6

```ActiveRecord::Base.on_slave do```

```
Zendesk Inclusive Language Check
/ Inclusive Language Check

Exclusive Language
Hi there! 👋 I see you used the term(s) [slave] here. This language is exclusionary for members of our community,
please consider changing it. For more info, see https://zendesk.atlassian.net/wiki/spaces/ENG/pages/631834099/Engineering+Inclusion
```

**Comment by ragurney** [comment]
Now that we have support for repo-specific settings in #18, what would you think about a `terms` subsetting to `ignore` where you could give an array of words that should be passed over? So the repo settings file would look something like:
```yaml
ignore:
  paths:
    - foo
    - bar/baz/
  terms:
    - on_slave
```

**Comment by rcclemente** [comment]
@ragurney 
looks good and provides a more readable path
